export const GET_ALL_MOVIES = 'GET_ALL_MOVIES'
export const GET_ALL_MOVIES_SUCCESS = 'GET_ALL_MOVIES_SUCCESS'
export const GET_ALL_MOVIES_FAILED = 'GET_ALL_MOVIES_FAILED'
export const GET_GENRES_START = 'GET_GENRES_START'
export const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS'
export const GET_GENRES_FAIL = 'GET_GENRES_FAIL'


