export const GET_ALL_UPCOMING_MOVIES = 'GET_ALL_UPCOMING_MOVIES';
export const GET_ALL_UPCOMING_MOVIES_SUCCESS =
  'GET_ALL_UPCOMING_MOVIES_SUCCESS';
export const GET_ALL_UPCOMING_MOVIES_FAILED = 'GET_ALL_UPCOMING_MOVIES_FAILED';
export const GET_ALL_POPULAR_MOVIES = 'GET_ALL_POPULAR_MOVIES';
export const GET_ALL_POPULAR_MOVIES_SUCCESS = 'GET_ALL_POPULAR_MOVIES_SUCCESS';
export const GET_ALL_POPULAR_MOVIES_FAILED = 'GET_ALL_POPULAR_MOVIES_FAILED';
export const GET_ALL_TOPRATED_MOVIES = 'GET_ALL_TOPRATED_MOVIES';
export const GET_ALL_TOPRATED_MOVIES_SUCCESS =
  'GET_ALL_TOPRATED_MOVIES_SUCCESS';
export const GET_ALL_TOPRATED_MOVIES_FAILED = 'GET_ALL_TOPRATED_MOVIES_FAILED';
export const GET_GENRES_START = 'GET_GENRES_START';
export const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
export const GET_GENRES_FAIL = 'GET_GENRES_FAIL';
export const GET_MOVIE_CREDITS = 'GET_MOVIE_CREDITS';
export const GET_MOVIE_CREDITS_SUCCESS = 'GET_MOVIE_CREDITS_SUCCESS';
export const GET_MOVIES_CREDITS_FAILS = 'GET_MOVIES_CREDITS_FAILS';
